In [1]:
# Импорт библиотек
import numpy as np
import pandas as pd

In [ ]:
!pip3 install scikit-learn --upgrade --user

In [ ]:
!pip install numpy==1.16.5 --user

1. Напишите программу, которая считывает с консоли числа (по одному в
строке) до тех пор, пока сумма введённых чисел не будет равна 0 и после
этого выводит сумму квадратов всех считанных чисел.

In [2]:
lst1 = []

while sum(lst1) != 0 or len(lst1) == 0:
    lst1.append(int(input()))

lst1 = [x ** 2 for x in lst1]
    
print(sum(lst1))

2
3
-6
1
50


2. Напишите программу, которая выводит последовательность чисел,
длинною N, где каждое число повторяется столько раз, чему оно равно.
На вход программе передаётся неотрицательное целое число N.
Например, если N = 7, то программа должна вывести 1 2 2 3 3 3 4. Вывод
элементов списка через пробел – print(*list).

In [3]:
N = int(input())
string = ''
board = 2*N - 1

for i in range(N):
    if len(string) < board:
        string = string + f'{i} ' * i

print(string[:board])

10
1 2 2 3 3 3 4 4 4 4


3. Матрицу произвольного размера вытянуть в один вектор, не применяя
встроенные методы Python.
Для создания матрицы можно использовать np.random.rand(кол-во
строк, кол-во столбцов).

In [4]:
n = int(input()) # количество столбцов
m = int(input()) # количество строк

mtrx1 = np.random.rand(n, m)
print(mtrx1, '\n')
print(mtrx1.reshape(1, n * m), '\n')
print(mtrx1.flatten())

2
3
[[0.81473006 0.67393757 0.44572655]
 [0.95928771 0.56619487 0.76183052]] 

[[0.81473006 0.67393757 0.44572655 0.95928771 0.56619487 0.76183052]] 

[0.81473006 0.67393757 0.44572655 0.95928771 0.56619487 0.76183052]


4. Даны два списка:

А = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]

В = [‘a’, ’b’, ’c’, ’c’, ’c’, ’b’, ’a’, ’c’, ’a’, ’a’, ’b’, ’c’, ’b’, ’a’]

Создать словарь, в котором ключи – это содержимое списка В, а
значения для ключей словаря – это сумма всех элементов списка А в
соответствии с буквой, содержащийся на той же позиции в списке В.
Пример результата программы: {‘a’ : 10, ‘b’ : 15, ‘c’ : 6}.

In [5]:
A = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

dictionary = dict.fromkeys(B)
sum_a, sum_b, sum_c = 0, 0, 0

for i in range(len(A)):
    if B[i] == 'a':
        sum_a += A[i]
    elif B[i] == 'b':
        sum_b += A[i]
    elif B[i] == 'c':
        sum_c += A[i]

dictionary['a'] = sum_a
dictionary['b'] = sum_b
dictionary['c'] = sum_c

print(dictionary)

{'a': 17, 'b': 11, 'c': 17}


5. Скачать и загрузить данные о стоимости домов в калифорнии,
используя библиотеку sklearn.

In [1]:
from sklearn.datasets import fetch_california_housing

df = fetch_california_housing(as_frame=True)

In [3]:
df.data.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24

6. Используя метод pd.concat([датафрейм1, датафрейм2], axis = 1),
добавить к данным столбец, содержащий информацию о медианной
стоимости дома (.target и .target_names).

In [6]:
series = pd.Series(df.target, name=df.target_names[0])
df.data = pd.concat([df.data, series], axis=1)

df.data.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521

7. Использовать метод info().

In [7]:
df.data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


8. Узнать, есть ли пропущенные значения, используя isna().sum().

In [8]:
df.data.isna().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

9. Вывести записи, где средний возраст домов в районе более 50 лет и
население более 2500 человек, используя метод loc().

In [9]:
df.data.loc[(df.data.HouseAge > 50) & (df.data.Population > 2500)]

MedInc  HouseAge  AveRooms  AveBedrms  Population    AveOccup  \
460    1.4012      52.0  3.105714   1.060000      3337.0    9.534286   
4131   3.5349      52.0  4.646119   1.047945      2589.0    5.910959   
4440   2.6806      52.0  4.806283   1.057592      3062.0    4.007853   
5986   1.8750      52.0  4.500000   1.206349      2688.0   21.333333   
7369   3.1901      52.0  4.730942   1.017937      3731.0    4.182735   
8227   2.3305      52.0  3.488860   1.170380      3018.0    3.955439   
13034  6.1359      52.0  8.275862   1.517241      6675.0  230.172414   
15634  1.8295      52.0  2.628169   1.053521      2957.0    4.164789   
15652  0.9000      52.0  2.237474   1.053535      3260.0    2.237474   
15657  2.5166      52.0  2.839075   1.184049      3436.0    1.621520   
15659  1.7240      52.0  2.278566   1.082348      4518.0    1.780142   
15795  2.5755      52.0  3.402576   1.058776      2619.0    2.108696   
15868  2.8135      52.0  4.584329   1.041169      2987.0    3.966799   

       Latitude  Longitude  MedHouseVal  
460       37.87    -122.26      1.75000  
4131      34.13    -118.20      1.93600  
4440      34.08    -118.21      1.53000  
5986      34.10    -117.71      2.12500  
7369      33.97    -118.21      1.67600  
8227      33.78    -118.20      1.62500  
13034     38.69    -121.15      2.25000  
15634     37.80    -122.41      2.43800  
15652     37.80    -122.41      5.00001  
15657     37.79    -122.41      2.75000  
15659     37.79    -122.41      2.25000  
15795     37.77    -122.42      3.25000  
15868     37.76    -122.41      2.60300

10. Узнать максимальное и минимальное значения медианной стоимости
дома (max(), min()).

In [10]:
print('minimum: ', df.data.MedHouseVal.min(), 
      '\nmaximum: ', df.data.MedHouseVal.max())

minimum:  0.14999 
maximum:  5.00001


11. Используя метод apply(), вывести на экран название признака и его
среднее значение.

In [11]:
def function(col):
    mean = col.mean()
    return mean

df.data.apply(function, axis=0)

MedInc            3.870671
HouseAge         28.639486
AveRooms          5.429000
AveBedrms         1.096675
Population     1425.476744
AveOccup          3.070655
Latitude         35.631861
Longitude      -119.569704
MedHouseVal       2.068558
dtype: float64